sudo: required
language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@6.3.0

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
